project_id = "ymolmtxhitmeuqdrfqih"

[functions.crosspost]
verify_jwt = false

[functions.track-ad-click]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.get-users-with-email]
verify_jwt = false
