project_id = "ymolmtxhitmeuqdrfqih"

[functions.crosspost]
verify_jwt = false

[functions.track-ad-click]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.get-users-with-email]
verify_jwt = false

[functions.import-archives]
verify_jwt = false

[functions.import-documents]
verify_jwt = false

[functions.import-news]
verify_jwt = false

[functions.import-blogs]
verify_jwt = false

[functions.import-galleries]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
